export const GET_TRACKS = 'GET_TRACKS'
export const LOADING_TRACKS = 'LOADING_TRACKS'
export const GET_IMAGE = 'GET_IMAGE'
export const LOADING_IMAGE = 'LOADING_IMAGE'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'