export const GET_TRACKS = 'GET_TRACKS'
export const LOADING_TRACKS = 'LOADING_TRACKS'
export const GET_ALBUM = 'GET_ALBUM'
export const LOADING_ALBUM = 'LOADING_ALBUM'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'